[package]
name = "dial"
version = "0.1.0"
authors = ["Evan Simmons <evan.simmons@creditkarma.com>"]

[dependencies]
futures = "0.1.21"
log = "0.4.1"
trust-dns-resolver = "0.9.0"
tokio = "0.1.6"
tokio-tcp = "0.1.0"
env_logger = "0.5.10"
